<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WebformNode_Webform_Dropdown</name>
   <tag></tag>
   <elementGuidId>f528231b-5039-4f8d-b21c-a88778e2ff58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-webform-0-target-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-target-id-webform-node-references webform-entity-select form-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-webform-0-target-id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>edit-webform-0-target-id--description</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-webform-0-target-id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>webform[0][target_id]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -ApplyContact UsContent Management IssuesContent Specialist Certification Sign-upContent Workshop Satisfaction SurveyDeep Dive WebformDigital Center of Excellence OrientationDrupal Consulting Sessions- Individual Session RequestDrupal Training RegistrationElement titles testGOVTalks: Accessibility SurveyGOVTalks: Content SurveyGOVTalks: Data SurveyGOVTalks: Fall 2016 SurveyGOVTalks: For the People, With the PeopleGOVTalks: Mobile Event SurveyGOVTalks: Social Media Workshop SurveyGOVTalks: Summer 2016 SurveyGOVTalks: The Future of Your Website SurveyGOVTalks: Usability Workshop SurveyGOVTalks Satisfaction Survey (Spring 2019)GOVTalks Spring 2019GOVTalks Survey (Fall 2018)Keena's webform testKeena 1:1 Test FormOne-on-One Training Sign-upRadio and CheckboxesResponsive Migration SurveySatisfaction Survey: Citizen Journey MappingSatisfaction Survey: Content MakeoverSatisfaction Survey: Content StrategySatisfaction Survey: Intro to Google Analytics TrainingSatisfaction Survey: PersonasSatisfaction Survey: Web AccessibilitySatisfaction Survey: Writing for the WebSign up for Our Mailing ListState Certified Content Workshop (structure)TestTEST-Confirmation Pagetest123Test AddressTest Consumer Site FormTest Content Strategy Satisfaction SurveyTest DocumentTesting ROOT-2452Test ROOT-2026Test Telephone AdvancedTest WebformTest Webform TrainingTraining Satisfaction SurveyWebsite Training RegistrationWhat to Expect at the Content Specialist CertificationWrite for Georgia.govQA test webform with automation 2961State Certified Content Workshop - Interest FormBasic Webform (structure)Basic Webform cloneContact Training</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-webform-0-target-id&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-webform-0-target-id']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-webform-wrapper']/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Webform'])[3]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='created'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the webform that you would like to attach to this node.'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Webform settings'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
